//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 12:31:10 PM CST 
//


package com.snowcat.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}job"/>
 *         &lt;element ref="{}qjob"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "job",
    "qjob"
})
@XmlRootElement(name = "jobs")
public class Jobs {

    @XmlElement(required = true)
    protected Job job;
    @XmlElement(required = true)
    protected Qjob qjob;

    /**
     * Gets the value of the job property.
     * 
     * @return
     *     possible object is
     *     {@link com.snowcat.config.Job }
     *     
     */
    public Job getJob() {
        return job;
    }

    /**
     * Sets the value of the job property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.snowcat.config.Job }
     *     
     */
    public void setJob(Job value) {
        this.job = value;
    }

    /**
     * Gets the value of the qjob property.
     * 
     * @return
     *     possible object is
     *     {@link com.snowcat.config.Qjob }
     *     
     */
    public Qjob getQjob() {
        return qjob;
    }

    /**
     * Sets the value of the qjob property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.snowcat.config.Qjob }
     *     
     */
    public void setQjob(Qjob value) {
        this.qjob = value;
    }

}
