//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 02:15:10 PM CST 
//


package com.snowcat.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.snowcat.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.snowcat.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.snowcat.config.Jobs }
     * 
     */
    public Jobs createJobs() {
        return new Jobs();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Datasource }
     * 
     */
    public Datasource createDatasource() {
        return new Datasource();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Sql }
     * 
     */
    public Sql createSql() {
        return new Sql();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Params }
     * 
     */
    public Params createParams() {
        return new Params();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Qjob }
     * 
     */
    public Qjob createQjob() {
        return new Qjob();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Qaction }
     * 
     */
    public Qaction createQaction() {
        return new Qaction();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Qsource }
     * 
     */
    public Qsource createQsource() {
        return new Qsource();
    }

    /**
     * Create an instance of {@link com.snowcat.config.Queue }
     * 
     */
    public Queue createQueue() {
        return new Queue();
    }

}
